log_sink sensitive to `progress`

diff --git a/tsk b/tsk
--- a/tsk
+++ b/tsk
@@ -29,17 +29,13 @@ exclusions="${exclusions:-}"
 # (in other words, you can rely on the default if you name your main class the same as the script file and ensure it has `main` method)
 main_class="${main_class:-}"
 
-# By default (`false`) TSK will output a log of it's internal operations (to the standard error stream)
-# only when a failure occur. This is to let you be able to pipe outputs of your script to other programs or files
-# without any additional clutter.
-# The TSK log is captured to a file in temporary directory and it's deleted right after display or when all goes well.
-# Sometimes you'll want to see what happens in the real time though, especially when some of the operations take longer
-# than expected, freeze or you want to see what happens exactly.
+# TSK only ever outputs its diagnostic information to standard error, so your script's standard output stays unpolluted.
+# The verbosity can be fined tuned by setting the `verbose` variable to:
 #
-# valid values:
-# - false - (default) output log to standard error on TSK failure, don't output anything if all goes well
-# - true - output log to standard error in the real time
-verbose="${verbose:-false}"
+# - false - output log to standard error only on TSK failure, don't output anything if all goes well
+# - just_progress (default) - output just the information about download progress, or everything if an error happened
+# - true - output all diagnostic information to the standard error in the real time
+verbose="${verbose:-just_progress}"
 
 # version of Coursier, the workhorse for JVM and library fetching
 coursier_version="${coursier_version:-v2.0.0}"
@@ -446,6 +442,10 @@ log_sink() {
   case "${verbose}" in
     "false")
       tee -a "${tsk_log}" > /dev/null;;
+    "just_progress")
+      local log_level="${1}"
+      local log_target="$([ "${log_level}" == "progress" ] && echo "/dev/stderr" || echo "/dev/null")"
+      tee -a "${tsk_log}" "${log_target}" > /dev/null;;
     "true")
       tee -a "${tsk_log}" /dev/stderr > /dev/null;;
     *)
@@ -455,7 +455,7 @@ log_sink() {
 
 run() {
   set -o pipefail
-  if (prepare_for_running_with_bloop 2>&1 | log_sink)
+  if (prepare_for_running_with_bloop 2>&1 | log_sink progress)
   then
     rm "${tsk_log}"
     eval "$(printf "%s" "exec_java $(
@@ -470,7 +470,7 @@ run() {
 
 run_with_ammonite() {
   set -o pipefail
-  if (install_coursier 2>&1 | log_sink)
+  if (install_coursier 2>&1 | log_sink  progress)
   then
     rm "${tsk_log}"
     eval "$(printf "%s" "exec_ammonite $(
